{% set name = "aiohttp-cors" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/aiohttp_cors/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ec70f38432c938e39d240ff38a7d789a5aa0a18087882c12d6cc141eef1144f6

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - aiohttp >=1.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - aiohttp_cors

about:
  home: https://github.com/aio-libs/aiohttp-cors
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'CORS support for aiohttp'
  doc_url: https://github.com/aio-libs/aiohttp-cors
  dev_url: https://github.com/aio-libs/aiohttp-cors

extra:
  recipe-maintainers:
    - carlodri
