{% set name = "aiohttp-cors" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/aiohttp_cors/{{ name }}-{{ version }}.tar.gz
  sha256: 4d39c6d7100fd9764ed1caf8cebf0eb01bf5e3f24e2e073fda6234bc48b19f5d

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=1.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - aiohttp_cors

about:
  home: https://github.com/aio-libs/aiohttp-cors
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'CORS support for aiohttp'
  doc_url: https://github.com/aio-libs/aiohttp-cors
  dev_url: https://github.com/aio-libs/aiohttp-cors

extra:
  recipe-maintainers:
    - carlodri
